
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[224] =
    {   0,
       47,   47,   55,   53,   36,   35,   52,   53,   34,   53,
       37,   38,   31,   30,   43,   32,   42,   33,   48,   48,
       44,   23,   28,   24,   47,   39,   40,   53,   53,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,    0,   51,    0,    0,    0,   41,   49,   27,
       49,   48,    0,    0,    0,    0,    0,    0,   48,    0,
       29,   25,   26,   47,   47,    0,    0,    0,   51,   47,
       47,   47,   47,   47,   47,    6,    4,   12,   47,   47,
       20,   47,   47,   47,   47,   47,   47,   47,    0,    0,
        0,    0,    0,    0,   50,    0,    0,    0,    0,    0,

        0,   49,    0,    0,   49,    0,   48,    0,    0,   48,
        0,    0,   49,   48,    0,    0,   48,    0,   48,    0,
       19,   47,   47,   47,    9,    1,   47,   47,   22,   47,
       47,   47,   47,   47,   47,   11,   47,   21,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   49,   49,    0,
        0,   49,   48,    0,   49,    0,   48,    0,    0,    0,
       48,    0,    0,   47,   47,    8,   47,    3,   13,   47,
       47,   47,    7,   10,   47,    0,    0,    0,    0,    0,
        0,   49,    0,   49,    0,    0,    0,    0,    0,   49,
       17,   47,   47,   47,   47,   47,    2,    0,    0,    0,

        0,    0,    0,   49,    0,   47,   47,   18,   47,   47,
        0,    0,   15,   14,    5,   16,    0,    0,    0,    0,
        0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    7,    5,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,    5,   22,
       23,   24,    5,    5,   25,   26,   25,   25,   27,   25,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   30,
       28,   28,   28,   28,   31,   28,   28,   32,   28,   28,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   48,   49,   48,   50,
       51,   52,   48,   53,   54,   55,   56,   57,   58,   59,
       60,   48,   61,   61,   61,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    3,    5,    5,    5,    5,
        3,    3,    3,    3,    6,    6,    6,    7,    7,    8,
        7,    7,    3,    3,    3,    3,    9,    3,    6,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    8,    7,    7,    7,    7,    7,    7,    7,    7,
        3
    } ;

static const flex_int16_t yy_base[262] =
    {   0,
        0,    0,  228,  789,  789,  789,  789,   56,  789,  190,
      789,  789,  789,  789,  789,  789,   48,  196,   76,   55,
      178,  169,  789,  164,   60,  789,  789,    0,  137,   67,
       56,   61,   71,   79,   75,   86,   62,   91,   97,   99,
      105,   95,   65,  125,  154,  160,  208,  789,  147,  789,
      159,  203,  214,  152,  254,  163,  103,  218,  260,  236,
      789,  789,  789,  117,  103,   93,   46,   43,  789,  153,
      146,  209,  231,  155,  162,  233,  238,  239,  245,  249,
      255,  268,  260,  269,  274,  261,  270,  278,  157,  211,
      315,    0,    0,    0,  789,   68,   61,  318,    0,    0,

        0,  321,  332,  336,  342,  353,  363,  357,  369,  232,
       71,  374,  378,  384,  390,    0,  389,  146,  405,  393,
      292,  377,  384,  385,  313,  364,  386,  393,  394,  400,
      401,  412,  406,  407,  420,  414,  419,  421,  458,    0,
        0,    0,  461,    0,    0,    0,  464,  468,  472,  476,
      483,  493,  480,   83,  501,  505,  489,  510,  502,  388,
      516,  523,  518,  497,  506,  508,  519,  510,  512,  521,
      523,  528,  527,  529,  540,  295,    0,    0,   56,    0,
        0,  567,  577,  581,  588,  514,  515,  572,  593,  597,
      538,  580,  578,  585,  572,  539,  570,    0,    0,    0,

        0,  599,  602,  623,  627,  599,  600,  605,  613,  614,
        0,    0,  609,  615,  619,  620,    0,    0,    0,    0,
        0,    0,  789,  671,  678,  683,  687,  694,  700,  705,
      710,  712,  714,  716,  718,  720,  722,  725,  730,  732,
      734,  736,  738,  740,  742,  747,  751,  753,  755,  757,
      759,  764,  766,  768,  770,  772,  774,  776,  778,  780,
      782
    } ;

static const flex_int16_t yy_def[262] =
    {   0,
      223,    1,  223,  223,  223,  223,  223,  224,  223,  225,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  226,  223,  223,  227,  228,  226,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,  224,  224,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  229,  223,  223,  223,
      223,  223,  223,  230,   30,  230,  230,  228,  223,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,  224,  224,
      223,  231,  232,  233,  223,  223,  223,  223,  234,  235,

      236,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  237,  238,  229,  223,  223,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,  223,  239,
      240,  241,  223,  242,  243,  244,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  245,  246,
      238,  223,  238,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,  224,  247,  248,  223,  249,
      250,  223,  223,  223,  223,  245,  245,  251,  223,  223,
       30,   30,   30,   30,   30,   30,   30,  252,  253,  254,

      255,  251,  251,  223,  223,   30,   30,   30,   30,   30,
      256,  257,   30,   30,   30,   30,  258,  259,  260,  261,
      253,  255,    0,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223
    } ;

static const flex_int16_t yy_nxt[851] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       21,   22,   23,   24,   25,   25,   25,   25,   25,   25,
       25,   25,   26,    4,   27,    4,   28,   29,   30,   31,
       25,   25,   32,   33,   25,   25,   34,   25,   35,   36,
       37,   25,   38,   25,   39,   25,   40,   41,   42,   25,
        4,   44,   48,   95,   49,   49,   49,   49,   95,   51,
       44,   59,   59,   59,   59,   95,   64,   64,   64,   64,
       69,   55,   66,   64,   64,   64,   64,  110,  110,   45,
       51,   60,   52,   52,   52,   53,   66,   55,   45,  153,

      153,   54,   55,   66,   56,   65,   72,   57,   65,   73,
       74,   65,   58,   65,   81,   54,   70,  116,   55,   71,
       65,   75,   76,   65,   65,   79,   56,   65,   77,   66,
       44,   65,   78,   82,   57,   65,   80,   86,   65,  118,
       65,   83,   84,   65,   65,   88,   65,   65,   65,   65,
       87,   65,   65,   66,   65,   65,   85,   65,   45,   89,
      223,   90,   44,  102,  102,  102,  102,   95,  110,  110,
       91,   91,   91,  103,   69,  105,  105,  105,  105,  114,
      114,  114,  223,  104,   92,  106,   63,   89,  111,  103,
       45,   62,   89,   89,  121,   65,  125,   89,  122,  115,

       61,  106,   65,   89,   65,   65,   89,   65,   89,   93,
       89,   65,   94,   96,  126,   97,   44,   51,   50,  107,
      107,  107,   53,   47,   98,   98,   98,  223,   51,   55,
       53,   53,   53,   53,   52,   52,   52,   53,   99,  108,
       55,   96,  223,  223,   45,   55,   96,   96,  153,  153,
      109,   96,   59,   59,   59,   59,   55,   96,   65,  123,
       96,   65,   96,  100,   96,  112,  101,  112,  154,  223,
      113,  113,  113,  113,   51,  223,  119,  119,  119,  119,
       65,  223,   65,   65,  124,   65,   55,   65,   65,  223,
       65,   65,  127,  223,   65,  128,  120,   65,   65,  223,

       44,   65,   55,  129,   65,  223,  130,   65,  131,   65,
       65,  134,   65,  136,  223,  133,  137,   65,   65,   65,
       65,   65,   65,   65,  132,  135,   65,   65,   45,  223,
      138,  139,  139,  139,  143,  143,  143,  102,  102,  102,
      102,   65,  223,  147,   65,  147,  223,  103,  148,  148,
      148,  148,  102,  102,  102,  102,  223,  104,  149,  149,
      149,  149,   65,  103,  151,   65,  151,  223,  106,  152,
      152,  152,  152,  107,  107,  107,   53,   51,  150,  107,
      107,  107,   53,  223,  106,   53,   53,   53,   53,   55,
      113,  113,  113,  113,  155,  155,  155,  155,  223,  108,

      157,  157,  157,  160,  223,   55,  114,  114,  114,  119,
      119,  119,  119,   65,  156,  164,   65,  162,  162,   51,
      158,  119,  119,  119,  119,  163,   65,  166,  167,   65,
      223,   55,  165,   65,   65,   65,   65,   65,   65,  162,
      162,  120,   65,   65,  168,   65,   65,   55,  169,   65,
       65,  170,   65,   65,  171,   65,  173,  223,   65,   65,
      172,   65,  174,   65,   65,  223,   65,  175,   65,   65,
       65,   65,   65,   65,  176,  176,  176,  179,  179,  179,
      148,  148,  148,  148,  182,  182,  182,  182,  149,  149,
      149,  149,  149,  149,  149,  149,  153,  153,  106,  152,

      152,  152,  152,  223,  183,  157,  157,  157,  150,  184,
      184,  184,  184,  223,  106,  223,  154,  155,  155,  155,
      155,  155,  155,  155,  155,  158,  157,  157,  157,  185,
      160,  162,  223,  223,  189,  223,  189,  156,  187,  190,
      190,  190,  190,  162,  223,  162,   65,  223,  192,   65,
      187,  223,  163,  162,  223,   65,  191,   65,   65,   65,
       65,   65,   65,  193,   65,  162,  223,  162,   65,  223,
       65,   65,   65,  194,  196,  195,   65,   65,   65,   65,
       65,   65,  197,  182,  182,  182,  182,   65,  210,   65,
       65,   65,   65,  182,  182,  182,  182,  184,  184,  184,

      184,  162,  223,  183,  184,  184,  184,  184,  203,  190,
      190,  190,  190,  204,  204,  204,  204,  185,  206,   65,
      207,   65,   65,  162,   65,  209,  208,   65,  162,   65,
       65,  223,   65,  205,   65,  203,  223,   65,  223,  204,
      204,  204,  204,  204,  204,  204,  204,  223,  213,   65,
      162,   65,  214,  223,   65,  215,  216,   65,   65,  205,
      223,   65,   65,   65,   65,   65,   65,   65,   65,   65,
      223,   65,   65,   43,   43,   43,   43,   43,   43,   43,
       46,   46,   46,   46,   46,   46,   46,   65,   65,   65,
       65,   65,   67,   67,   67,   68,   68,   68,   68,   68,

       68,   68,   68,  117,  117,  117,  223,  223,  117,   64,
       64,   64,   64,   64,  140,  140,  141,  141,  142,  142,
      144,  144,  145,  145,  146,  146,  159,  159,  161,  161,
      161,  223,  161,  161,  177,  177,  178,  178,  176,  176,
      180,  180,  181,  181,  179,  179,  186,  186,  223,  186,
      186,  188,  188,  223,  188,  198,  198,  199,  199,  200,
      200,  201,  201,  202,  202,  223,  202,  202,  211,  211,
       43,   43,  212,  212,   46,   46,  217,  217,  218,  218,
      219,  219,  220,  220,  221,  221,  222,  222,    3,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223
    } ;

static const flex_int16_t yy_chk[851] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,   17,  179,   17,   17,   17,   17,   97,   20,
       43,   20,   20,   20,   20,   96,   25,   25,   25,   25,
       68,   20,   67,   30,   30,   30,   30,  111,  111,    8,
       19,   20,   19,   19,   19,   19,   25,   20,   43,  154,

      154,   19,   19,   30,   19,   31,   31,   19,   31,   32,
       32,   37,   19,   32,   37,   19,   30,   57,   19,   30,
       33,   33,   34,   33,   35,   35,   19,   35,   34,   66,
       44,   34,   34,   38,   19,   36,   36,   40,   36,   57,
       38,   38,   39,   38,   42,   42,   39,   42,   40,   39,
       41,   40,   65,   64,   41,   65,   39,   41,   44,   45,
      118,   45,   89,   49,   49,   49,   49,   46,   54,   54,
       45,   45,   45,   49,   29,   51,   51,   51,   51,   56,
       56,   56,  118,   49,   45,   51,   24,   45,   54,   49,
       89,   22,   45,   45,   70,   71,   74,   45,   71,   56,

       21,   51,   70,   45,   74,   70,   45,   74,   45,   45,
       45,   75,   45,   47,   75,   47,   90,   52,   18,   52,
       52,   52,   52,   10,   47,   47,   47,    3,   53,   52,
       53,   53,   53,   53,   58,   58,   58,   58,   47,   52,
       53,   47,    0,    0,   90,   52,   47,   47,  110,  110,
       53,   47,   60,   60,   60,   60,   53,   47,   72,   72,
       47,   72,   47,   47,   47,   55,   47,   55,  110,    0,
       55,   55,   55,   55,   59,    0,   59,   59,   59,   59,
       73,    0,   76,   73,   73,   76,   59,   77,   78,    0,
       77,   78,   77,    0,   79,   79,   59,   79,   80,    0,

      176,   80,   59,   80,   81,    0,   82,   81,   82,   83,
       86,   84,   83,   86,    0,   83,   87,   82,   84,   87,
       82,   84,   87,   85,   82,   85,   85,   88,  176,    0,
       88,   91,   91,   91,   98,   98,   98,  102,  102,  102,
      102,  121,    0,  103,  121,  103,    0,  102,  103,  103,
      103,  103,  104,  104,  104,  104,    0,  102,  105,  105,
      105,  105,  125,  102,  106,  125,  106,    0,  105,  106,
      106,  106,  106,  108,  108,  108,  108,  107,  105,  107,
      107,  107,  107,    0,  105,  109,  109,  109,  109,  107,
      112,  112,  112,  112,  113,  113,  113,  113,    0,  107,

      114,  114,  114,  117,    0,  107,  115,  115,  115,  120,
      120,  120,  120,  126,  113,  122,  126,  160,  117,  119,
      114,  119,  119,  119,  119,  117,  122,  124,  127,  122,
        0,  119,  123,  123,  124,  127,  123,  124,  127,  160,
      117,  119,  128,  129,  128,  128,  129,  119,  130,  130,
      131,  131,  130,  131,  132,  133,  134,    0,  133,  134,
      133,  132,  135,  136,  132,    0,  136,  137,  137,  135,
      138,  137,  135,  138,  139,  139,  139,  143,  143,  143,
      147,  147,  147,  147,  148,  148,  148,  148,  149,  149,
      149,  149,  150,  150,  150,  150,  153,  153,  149,  151,

      151,  151,  151,    0,  148,  157,  157,  157,  149,  152,
      152,  152,  152,    0,  149,    0,  153,  155,  155,  155,
      155,  156,  156,  156,  156,  157,  158,  158,  158,  152,
      161,  159,  163,    0,  162,    0,  162,  155,  159,  162,
      162,  162,  162,  186,  187,  161,  164,  163,  165,  164,
      186,  187,  161,  159,  163,  165,  164,  166,  165,  168,
      166,  169,  168,  167,  169,  186,  187,  161,  167,  163,
      170,  167,  171,  170,  172,  171,  173,  172,  174,  173,
      172,  174,  175,  182,  182,  182,  182,  191,  196,  175,
      191,  196,  175,  183,  183,  183,  183,  184,  184,  184,

      184,  188,    0,  182,  185,  185,  185,  185,  188,  189,
      189,  189,  189,  190,  190,  190,  190,  184,  192,  197,
      193,  195,  197,  188,  195,  195,  194,  193,  202,  192,
      193,  203,  192,  190,  194,  202,    0,  194,  203,  204,
      204,  204,  204,  205,  205,  205,  205,    0,  206,  207,
      202,  206,  207,  203,  208,  209,  210,  208,  213,  204,
        0,  213,  209,  210,  214,  209,  210,  214,  215,  216,
        0,  215,  216,  224,  224,  224,  224,  224,  224,  224,
      225,  225,  225,  225,  225,  225,  225,  226,  226,  226,
      226,  226,  227,  227,  227,  228,  228,  228,  228,  228,

      228,  228,  228,  229,  229,  229,    0,    0,  229,  230,
      230,  230,  230,  230,  231,  231,  232,  232,  233,  233,
      234,  234,  235,  235,  236,  236,  237,  237,  238,  238,
      238,    0,  238,  238,  239,  239,  240,  240,  241,  241,
      242,  242,  243,  243,  244,  244,  245,  245,    0,  245,
      245,  246,  246,    0,  246,  247,  247,  248,  248,  249,
      249,  250,  250,  251,  251,    0,  251,  251,  252,  252,
      253,  253,  254,  254,  255,  255,  256,  256,  257,  257,
      258,  258,  259,  259,  260,  260,  261,  261,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Analyser.l"
#line 2 "Analyser.l"
#include <stdio.h>
#include <stdlib.h>

#include "Analyser.tab.h"
//void yyerror (char *s);
//int yylex();

//used in error function
int line_no = 1;
int errors = 0;
#line 722 "lex.yy.c"
/* Integer literals*/
/* floating piont literals*/
/*Rune literals*/
/*String Literal*/
/*"*/
#line 728 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 104 "Analyser.l"


#line 948 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 224 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 789 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 106 "Analyser.l"
{ return( T_FOR );}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 107 "Analyser.l"
{ return( T_WHILE );}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 108 "Analyser.l"
{ return( T_LOOP );}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 109 "Analyser.l"
{ return( T_IN );}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 110 "Analyser.l"
{ return( T_REVERSE );}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "Analyser.l"
{ return( T_IF );}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 112 "Analyser.l"
{ return( T_THEN );}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "Analyser.l"
{ return( T_ELSE );}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 114 "Analyser.l"
{ return( T_END );}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "Analyser.l"
{ return( T_TYPE );}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 116 "Analyser.l"
{ return( T_VAR );}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 117 "Analyser.l"
{ return( T_IS );}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 120 "Analyser.l"
{ return( T_REAL );}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 121 "Analyser.l"
{ return( T_INTEGER );}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "Analyser.l"
{ return( T_BOOLEAN );}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "Analyser.l"
{ return( T_ROUTINE );}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "Analyser.l"
{ return(T_ARRAY );}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "Analyser.l"
{ return(T_RECORD );}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 127 "Analyser.l"
{ return( T_AND );}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 128 "Analyser.l"
{ return( T_OR );}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 129 "Analyser.l"
{ return( T_XOR );}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "Analyser.l"
{ return(T_NOT);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 132 "Analyser.l"
{ return( T_LESS );}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 133 "Analyser.l"
{ return( T_GREAT );}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 134 "Analyser.l"
{ return( T_LESSOREQU );}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "Analyser.l"
{ return( T_GREATOREQU );}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 136 "Analyser.l"
{ return( T_NOTEQU );}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 137 "Analyser.l"
{ return( T_EQU );}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 138 "Analyser.l"
{ return( T_COLONEQU ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 141 "Analyser.l"
{ return( T_ADDOP );}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "Analyser.l"
{ return( T_MULTOP );}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 143 "Analyser.l"
{ return( T_SUBTROP );}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "Analyser.l"
{ return( T_DIVOP );}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 145 "Analyser.l"
{ return( T_MOD );}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 147 "Analyser.l"
{line_no++; return( T_NL ); /*printf("Line is right %d \n", line_no); return( T_NL);*/}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 148 "Analyser.l"
{ return( T_TAB ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 151 "Analyser.l"
{ return( T_LPAREN );}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 152 "Analyser.l"
{ return( T_RPAREN );}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "Analyser.l"
{ return( T_LBRACK );}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "Analyser.l"
{ return( T_RBRACK );}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 156 "Analyser.l"
{ return( T_DOTDOT );}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "Analyser.l"
{ return( T_DOT );}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 158 "Analyser.l"
{ return( T_COMMA );}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 159 "Analyser.l"
{ return( T_COLON );}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 160 "Analyser.l"
{ return( T_ASSIGN );}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 161 "Analyser.l"
{ return( T_ASSIGNOP );}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 164 "Analyser.l"
{ /*yylval.string = strdup(yytext);*/ return( T_ID );} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 166 "Analyser.l"
{/*yylval.integer = atoi(yytext); */        return(T_ICONST );}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 167 "Analyser.l"
{/*yylval.real = decRealHandler(yytext);*/  return( T_RCONST );}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 168 "Analyser.l"
{/*yylval.character=yytext[1];*/            return( T_CCONST );}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 169 "Analyser.l"
{/*yylval.string = yytext.substr(1, yytext.size() - 2);*/ return( T_SCONST );}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 171 "Analyser.l"
{ return( T_EOF );}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 173 "Analyser.l"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 174 "Analyser.l"
{ECHO; printf ("unexpected character");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 176 "Analyser.l"
ECHO;
	YY_BREAK
#line 1281 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 224 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 224 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 223);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "Analyser.l"

int yywrap (void) {return 1;}
